""" URLs and other constants """

URL_CONFIRMED = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"
URL_DEATH = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"
URL_RECOVERED = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"
FILE_CONFIRMED = "cases_confirmed.csv"
FILE_DEATH = "cases_death.csv"
FILE_RECOVERED = "cases_recovered.csv"
FILE_BOKEH = "bokeh.html"
FILE_BOKEH_EMBED_DETAILS = "embed_details.bokeh"
FILE_BOKEH_EMBED_STACKS = "embed_stacks.bokeh"
FILE_BOKEH_EMBED_SELECTORS = "embed_selector.bokeh"
